Use file name for the external commands (fixes #889)
infinyon/fluvio pull request #1008
Opened 2021-04-24 15:46 UTC by avinassh

Ran into this issue myself, I thought I'd send a patch. Here is the new output now:

```shell 
$ cargo run

Fluvio command-line interface

fluvio-cli [FLAGS] [OPTIONS] <SUBCOMMAND>

FLAGS:
        --tls                   Enable TLS
        --enable-client-cert    TLS: use client cert
    -h, --help                  Prints help information

OPTIONS:
    -c, --cluster <host:port>          Address of cluster
        --domain <domain>              Required if client cert is used
        --ca-cert <ca-cert>
            Path to TLS ca cert, required when client cert is enabled

        --client-cert <client-cert>    Path to TLS client certificate
        --client-key <client-key>      Path to TLS client private key
    -P, --profile <profile>

SUBCOMMANDS:
    consume         Read messages from a topic/partition
    produce         Write messages to a topic/partition
    topic           Manage and view Topics
    partition       Manage and view Partitions
    profile         Manage Profiles, which describe linked clusters
    cluster         Install or uninstall Fluvio clusters
    install         Install Fluvio plugins
    update          Update the Fluvio CLI
    version         Print Fluvio version information
    fluvio-cloud    Cloud Operations
    help            Prints this message or the help of the given
                    subcommand(s)
```

2021-04-24 16:02 UTC, nicholastmosher requested changes
Thanks for the PR @avinassh, it's greatly appreciated!

External subcommands have filenames with the prefix `fluvio-`, such as `fluvio-cloud`, but the name of the subcommand that should show up in the help menu should be everything after the prefix. In the `fluivo-cloud` example, `cloud` should be displayed in help. I think `str::strip_prefix("fluvio-")` would work nicely here.

One nit: could you use a match statement instead of `if-let/else`?

Thanks!

2021-04-24 17:18 UTC, avinassh commented
> External subcommands have filenames with the prefix fluvio-, such as fluvio-cloud, but the name of the subcommand that should show up in the help menu should be everything after the prefix

Is this always guaranteed and I can call unwrap on `str::strip_prefix` OR should I handle the `None` case as well?

2021-04-26 21:00 UTC, nicholastmosher commented
I think the representation in the help menu is a different issue than this. Fixing it would probably require editing the help menu template used by structopt/clap. Also just FYI, `fluvio-cloud` currently belongs to a private repo which is why you wouldn't have found it

2021-04-27 07:14 UTC, avinassh commented
> I think the representation in the help menu is a different issue than this. 

yeah, actually you are right. btw do you could tell me about the other thing:

> Is this always guaranteed and I can call unwrap on str::strip_prefix OR should I handle the None case as well?

2021-04-27 13:15 UTC, nicholastmosher commented
@avinassh in the current implementation, it should be guaranteed, yes: https://github.com/infinyon/fluvio/blob/master/src/cli/src/install/mod.rs#L43-L58

I'd say let's move forward using that unwrap, and if anything changes such that this would actually panic, we'll consider those changes a bug and we'll update accordingly at that time.

2021-04-27 13:56 UTC, avinassh commented
Nice! I have updated the PR. 

```shell
$ cargo run -- --help

// snipped

SUBCOMMANDS:
    consume      Read messages from a topic/partition
    produce      Write messages to a topic/partition
    topic        Manage and view Topics
    partition    Manage and view Partitions
    profile      Manage Profiles, which describe linked clusters
    cluster      Install or uninstall Fluvio clusters
    install      Install Fluvio plugins
    update       Update the Fluvio CLI
    version      Print Fluvio version information
    cloud        Cloud Operations
    help         Prints this message or the help of the given subcommand(s)
```

2021-04-27 14:28 UTC, nicholastmosher approved these changes
Looks great! Thanks @avinassh!

2021-04-27 18:45 UTC, nicholastmosher commented
bors r+

2021-04-27 19:15 UTC, closed without merging