[Merged by Bors] - Stabilize upgrade testing in CI
infinyon/fluvio pull request #1073
Opened 2021-05-11 05:01 UTC by tjtelan

Fixes #1066

We've found more stability in CI by slowing down calls to the `fluvio` cluster. (The test output prints cpu load avgs, which are frequently overscheduled.)

Upgrade test is driven by shell script `test/upgrade-test.sh`. 

---

We've found more stability in CI by slowing down calls to the `fluvio` cluster. (The test output prints cpu load avgs, which are frequently overscheduled.)

Test data and checksums are generated prior to cluster installation.

We test 3 versions: Last stable, current stable and then we compile and install the repo version.

---

For each version, we create a new topic, produce and consume then verify content w/ checksum. Then we verify functionality old topics after upgrade with a consume, produce, consume + checksum verification.

2021-05-11 18:59 UTC, sehz commented
@nicholastmosher Please review this as well

2021-05-11 19:18 UTC, sehz requested changes
Looks good.  Couple of minor comments

2021-05-11 19:18 UTC, sehz commented on .github/workflows/ci.yml
> +          minikube version: 'v1.16.0'
try latest `1.18.1`

2021-05-11 19:18 UTC, sehz commented on .github/workflows/ci.yml
> +          kubernetes version: 'v1.19.2'
we are using 1.19.6

2021-05-11 19:18 UTC, nicholastmosher commented on .github/workflows/ci.yml
> +            ./upgrade-test.sh `gh release -R infinyon/fluvio list | head -3 | tail -2 | awk '{print $1}' | sed 's/v//' | tac | xargs`
This can probably be simplified to

```
gh api repos/infinyon/fluvio/releases -q '.[2,1].tag_name' | sed 's/v//'
0.8.1
0.8.2
```

2021-05-11 19:19 UTC, nicholastmosher commented on .github/workflows/ci.yml
> +            ./upgrade-test.sh `gh release -R infinyon/fluvio list | head -3 | tail -2 | awk '{print $1}' | sed 's/v//' | tac | xargs`
Also instead of using backticks for inline commands it is better practice to use `$(...)`

2021-05-11 20:08 UTC, nicholastmosher commented
It seems like a lot of this upgrade-test script can be abstracted into bash functions, I'd maybe try to make a function for running tests on a topic, where the topic is given as an argument, for example. I also definitely recommend reading through https://kfirlavi.herokuapp.com/blog/2012/11/14/defensive-bash-programming/ and using some tips from there

2021-05-11 23:56 UTC, tjtelan commented on .github/workflows/ci.yml
> +            ./upgrade-test.sh `gh release -R infinyon/fluvio list | head -3 | tail -2 | awk '{print $1}' | sed 's/v//' | tac | xargs`
Added a comment. The purpose of the one-liner is to get the stable and stable-1 versions. And we pass them into the script to configure the CLI and cluster versions we are going to test.

2021-05-11 23:58 UTC, tjtelan commented on tests/upgrade-test.sh
> +STABLE_MINUS_ONE=${1:?Starting cluster version [pos 1]}
The purpose was just to have some error thrown when the input validation (`:?`) fails. If no version is passed for argv[1] (or it is null) then we halt execution and throw the error. I changed the message to be a bit more descriptive

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02

2021-05-12 05:50 UTC, tjtelan commented
> It seems like a lot of this upgrade-test script can be abstracted into bash functions, I'd maybe try to make a function for running tests on a topic, where the topic is given as an argument, for example. I also definitely recommend reading through https://kfirlavi.herokuapp.com/blog/2012/11/14/defensive-bash-programming/ and using some tips from there

Definitely hear you, but I'm not sure what is gained out of extra abstraction in this specific internal use-case. The suggestion is much bigger than the problem being solved.

Checksums for each new write to a topic are calculated w/r/t the number of versions we plan on testing, and refactoring into a more stateful or functional style is not going to be trivial in Bash, (or easier to read).

In my opinion, flattening the cli x cluster convolution seems worth the effort only if we plan to test more than 3 versions, like we support in this test.

2021-05-12 14:04 UTC, sehz commented
I think this PR is ready to go.  @nicholastmosher agree?

2021-05-12 14:07 UTC, nicholastmosher approved these changes
LGTM

2021-05-12 14:13 UTC, sehz commented
bors r+

2021-05-12 14:14 UTC, sehz commented
@nicholastmosher @tjtelan Once this is merged. This should be put as mandatory for Bors?

2021-05-12 14:17 UTC, nicholastmosher commented
@sehz I think it eventually should be, but let's maybe give this a week or two to run as non-required so that we can be sure that things are working as expected, then we can promote it to required

2021-05-12 15:23 UTC, closed without merging