Instrument SPU
infinyon/fluvio pull request #1125
Opened 2021-05-25 20:37 UTC by nicholastmosher

- Adds `#[tracing::instrument]` to more areas in the SPU to support better tracing e.g. with otel/jaeger

2021-05-25 23:50 UTC, sehz commented
rebase

2021-05-28 01:32 UTC, sehz commented
rebase to make CI success

2021-05-28 01:34 UTC, sehz requested changes
just couple of nits

2021-05-28 01:34 UTC, sehz commented on src/spu/src/control_plane/message_sink.rs
> +    #[instrument]
too low level. remove this

2021-05-28 01:34 UTC, sehz commented on src/spu/src/control_plane/message_sink.rs
> +    #[instrument(skip(self, request))]
remove

2021-05-28 01:34 UTC, sehz commented on src/spu/src/control_plane/message_sink.rs
> +    #[instrument(skip(self))]
remove

2021-05-28 01:34 UTC, sehz commented on src/spu/src/replication/leader/replica_state.rs
> +    #[instrument(skip(self))]
remove

2021-06-03 14:15 UTC, nicholastmosher commented
@sehz rebased

2021-06-03 23:02 UTC, sehz approved these changes
LGTM

2021-06-03 23:02 UTC, sehz commented
bors r+

2021-06-04 12:12 UTC, nicholastmosher commented
bors ping

2021-06-04 12:12 UTC, nicholastmosher commented
bors r+

2021-06-04 12:55 UTC, closed without merging