Instrument misc
infinyon/fluvio pull request #1127
Opened 2021-05-25 20:37 UTC by nicholastmosher

- Adds `#[tracing::instrument]` to more areas in misc crates to support better tracing e.g. with otel/jaeger

2021-05-28 01:38 UTC, sehz commented
rebase to get clean diff

2021-06-03 14:14 UTC, nicholastmosher commented
@sehz rebased

2021-06-03 23:01 UTC, sehz requested changes
minor nits

2021-06-03 23:01 UTC, sehz commented on src/protocol/fluvio-protocol-api/src/request.rs
>      fn decode<T>(&mut self, src: &mut T, version: Version) -> Result<(), IoError>
These are very low level call, it just add lots of noise, is there any benefit to add tracing?

2021-06-04 12:26 UTC, nicholastmosher commented
I took a look at Jaeger and didn't see any place where these spans were really showing up, so for now they're not adding any value, I'll remove them.

2021-06-04 12:58 UTC, sehz approved these changes

2021-06-04 13:09 UTC, nicholastmosher commented
bors r+

2021-06-04 14:26 UTC, closed without merging