feat: Add 'fluvio produce --raw' for sending whole files
infinyon/fluvio pull request #1148
Opened 2021-06-03 21:36 UTC by nicholastmosher

Closes #1139.

- Adds `fluvio produce <topic> --raw` flag to indicate that input should be sent as one full record, rather than broken down by lines.

2021-06-03 23:15 UTC, sehz requested changes
minor nit.  Can you add to changelog ?

2021-06-04 13:02 UTC, sehz requested changes
This should go into 0.8.4

2021-06-04 13:08 UTC, nicholastmosher commented
Oh whoops

2021-06-04 13:12 UTC, sehz approved these changes

2021-06-04 13:21 UTC, nicholastmosher commented
bors r+

2021-06-04 15:10 UTC, closed without merging