Smartstream map
infinyon/fluvio pull request #1174
Opened 2021-06-16 16:33 UTC by nicholastmosher

Closes #1172 

This is updated since our first iteration of SmartStreams with filter. Users can write a mapping SmartStream like the following now:

```rust
#[smartstream(map)]
pub fn map(mut record: Record) -> Record {
    let mut value = Vec::from(record.value.as_ref());
    value.make_ascii_uppercase();
    record.value = RecordData::from(value);
    record
}
```

This gives the following results:

```
flvd consume test -B
one
two
Three
fouR
```

```
❯ flvd consume test -B --smart-stream=examples/target/wasm32-unknown-unknown/release/fluvio_wasm_map.wasm
ONE
TWO
THREE
FOUR
```

2021-06-16 16:52 UTC, nicholastmosher commented
I am thinking of writing another example for this, possibly something to do with JSON, similar to the filter_json example

2021-06-21 10:47 UTC, nicholastmosher commented
@sehz this has been updated with the latest API we discussed in #1172, it is now ready to review

2021-06-21 17:45 UTC, sehz requested changes
LGTM.  Nice job. To finish this, 
- bump up version
- add to changelog

2021-06-21 19:02 UTC, sehz requested changes

2021-06-21 19:02 UTC, sehz commented on src/dataplane-protocol/src/record.rs
> +#[derive(Clone, Default)]
this requires bump up version for dataplane-protocol

2021-06-21 20:55 UTC, sehz commented on src/smartstream/Cargo.toml
>  fluvio-dataplane-protocol = { version = "0.5.1", path = "../dataplane-protocol", default-features = false }
this should be 0.5.2?

2021-06-21 21:01 UTC, nicholastmosher commented on src/smartstream/Cargo.toml
>  fluvio-dataplane-protocol = { version = "0.5.1", path = "../dataplane-protocol", default-features = false }
Ah yep. Updated dependencies

2021-06-21 21:27 UTC, sehz requested changes
only need to update smartstream's dependencies

2021-06-21 21:27 UTC, sehz commented on src/auth/Cargo.toml
> +dataplane = { version = "0.5.2", path = "../dataplane-protocol", package = "fluvio-dataplane-protocol" }
no need for updating this

2021-06-21 21:27 UTC, sehz commented on src/client/Cargo.toml
> +dataplane = { version = "0.5.2", path = "../dataplane-protocol", package = "fluvio-dataplane-protocol" }
no need

2021-06-21 21:27 UTC, sehz commented on src/controlplane-metadata/Cargo.toml
> +dataplane = { version = "0.5.2", path = "../dataplane-protocol", package = "fluvio-dataplane-protocol" }
no need

2021-06-21 21:27 UTC, sehz commented on src/controlplane/Cargo.toml
> -dataplane = { version = "0.5.1", path = "../dataplane-protocol", package = "fluvio-dataplane-protocol" }
no need

2021-06-21 21:27 UTC, sehz commented on src/sc-schema/Cargo.toml
> -dataplane = { version = "0.5.1", path = "../dataplane-protocol", package = "fluvio-dataplane-protocol" }
no need

2021-06-21 21:27 UTC, sehz commented on src/sc/Cargo.toml
> +dataplane = { version = "0.5.2", path = "../dataplane-protocol", package = "fluvio-dataplane-protocol" }
no need

2021-06-22 17:41 UTC, sehz requested changes

2021-06-22 17:41 UTC, sehz commented on src/spu-schema/Cargo.toml
> +dataplane = { version = "0.5.2", path = "../dataplane-protocol", package = "fluvio-dataplane-protocol" }
this doesn't need to be updated

2021-06-22 17:41 UTC, sehz commented on src/spu/Cargo.toml
> +dataplane = { version = "0.5.2", path = "../dataplane-protocol", package = "fluvio-dataplane-protocol" , features=["file"]}
same here

2021-06-22 17:41 UTC, sehz commented on src/storage/Cargo.toml
> +dataplane = { version = "0.5.2", path = "../dataplane-protocol", package = "fluvio-dataplane-protocol", features = ["file"] }
same

2021-06-23 18:32 UTC, sehz approved these changes
LGTM

2021-06-23 18:33 UTC, sehz commented
bors r+

2021-06-23 19:21 UTC, closed without merging