Flv test updates
infinyon/fluvio pull request #1252
Opened 2021-07-16 06:31 UTC by tjtelan

2021-07-25 18:28 UTC, sehz requested changes
This too big a PR.  We should break this into a smaller PR:

2021-07-25 18:28 UTC, sehz commented on tests/runner/Cargo.toml
> +sysinfo = "0.19.1"
we should create different feature flag. By default, performance run be disabled.  Pulsar and Kafka run should be also made as optional. 

Another thought  is to create separate runner for performance

2021-07-25 18:28 UTC, sehz commented on tests/runner/src/main.rs
> +        if &option.environment.cluster_type == "fluvio" {
Instead of matching string, map cluster type to enum in the arg

2021-07-25 18:28 UTC, sehz commented on tests/runner/src/main.rs
> +        let system_profiler_client = fluvio_client.clone();
this should be made put under feature flag or make as optional

2021-07-25 18:28 UTC, sehz commented on tests/runner/src/main.rs
> +            let mut s = System::new_all();
move this into separate module or async function to make this more modular

2021-07-25 18:28 UTC, sehz commented on tests/runner/src/main.rs
> +        if &option.environment.cluster_type == "fluvio" {
use environment driver rathe than hard code this

2021-07-25 18:28 UTC, sehz commented on tests/runner/src/main.rs
> +            if !option.runner_opts.skip_data_save {
move this into chart module

2021-07-25 18:28 UTC, sehz commented on tests/runner/src/main.rs
> +    match option.environment.cluster_type.as_str() {
move this under environment driver rather than hard coding them

2021-07-25 18:28 UTC, sehz commented on tests/runner/src/main.rs
> +        "pulsar" => Arc::new(RwLock::new(
pulsar and kafka should under feature flag

2021-07-26 02:34 UTC, tjtelan commented
@sehz Sure, I can break this up into smaller pieces. I was just hoping that we're now able to commit to the data it produces currently? 

If we're happy with the numbers that we're collecting (like good enough for publishing in a blog post) then there shouldn't be any more changes needed other than what you've requested.

2021-07-26 02:50 UTC, sehz commented
That discussion is out of scope for this PR

2021-08-05 16:26 UTC, tjtelan commented
Closing in favor of #1380 - I'll bring this branch into the repo with split up PRs

2021-08-05 16:26 UTC, closed without merging