Spu smartstream errors
infinyon/fluvio pull request #1327
Opened 2021-07-29 04:12 UTC by nicholastmosher

Second sub-piece of https://github.com/infinyon/fluvio/pull/1226

Review/merge after https://github.com/infinyon/fluvio/pull/1326

2021-07-30 23:45 UTC, nicholastmosher commented
@sehz I've updated this next smartstream-error PR, let me know if you have any feedback before merging

2021-07-30 23:52 UTC, sehz commented on src/spu/src/services/public/stream_fetch.rs
> +                    // Just save the leader offset and continue waiting for events.
nice comment!

2021-07-31 00:00 UTC, sehz requested changes
Overall looks good.  2 comments here

2021-08-01 01:10 UTC, nicholastmosher commented on src/spu/src/services/public/stream_fetch.rs
Note that this test you commented on is test_filter_stream_max, which is focused on checking max bytes. The other tests do check that if a response is sent, it contains both the correct records and any error that occurred.

2021-08-01 02:00 UTC, sehz commented on src/smartstream/derive/src/generator/filter.rs
> +use quote::quote;
this is not show stopper but we should reduce duplication

2021-08-01 02:08 UTC, sehz approved these changes
Great job.  This was huge undertaking

2021-08-01 02:08 UTC, sehz commented
bors r+

2021-08-01 02:30 UTC, closed without merging