Add check for unused dependencies
infinyon/fluvio pull request #1377
Opened 2021-08-04 22:56 UTC by tjtelan

Resolves #415

* Install nightly in CI (to be used by udeps)
* Add udeps to Makefile
* Remove unused crates and minor bumped affected crates

2021-08-05 20:29 UTC, sehz requested changes
excellent cleanup. minor changed needed

2021-08-05 20:29 UTC, sehz commented on .github/workflows/ci.yml
> +        rust: [stable, nightly]
should use include rather than put requirement for nightly for all checks

2021-08-05 20:29 UTC, sehz commented on .github/workflows/ci.yml
> +        if: ${{ matrix.rust == 'stable' && matrix.check == 'fmt' }}
don't need for checking stable if you use `include` in the matrix

2021-08-16 21:14 UTC, sehz approved these changes

2021-08-16 21:50 UTC, sehz commented
bors r+

2021-08-16 21:54 UTC, sehz commented
bors r-

2021-08-16 21:55 UTC, sehz commented
building check dependencies seems to take long.  Can you cache them?

2021-08-17 23:51 UTC, tjtelan commented
Here's what I learned after digging into this more. I'm not sure how we want to proceed.

We are using `rust-cache` to configure our caching for this job. 

We get a cache-miss at the beginning of most of the jobs

```
Restoring paths:
    /home/runner/.cargo/bin
    /home/runner/.cargo/.crates2.json
    /home/runner/.cargo/.crates.toml
    /home/runner/.cargo/git
    /home/runner/.cargo/registry/cache
    /home/runner/.cargo/registry/index
    ./target
In directory:
    /home/runner/work/fluvio/fluvio
Using keys:
    v0-rust-x86_64-unknown-linux-gnu-unused-dependencies-check-1.56.0-nightly-x86_64-unknown-linux-gnu-2d2bc94c8c3a-1f638b2bd5788a73a101
    v0-rust-x86_64-unknown-linux-gnu-unused-dependencies-check-1.56.0-nightly-x86_64-unknown-linux-gnu-2d2bc94c8c3a
No cache found.
```

and we're caching the result of our build.

```
Saving paths:
    /home/runner/.cargo/bin
    /home/runner/.cargo/.crates2.json
    /home/runner/.cargo/.crates.toml
    /home/runner/.cargo/git
    /home/runner/.cargo/registry/cache
    /home/runner/.cargo/registry/index
    ./target
In directory:
    /home/runner/work/fluvio/fluvio
Using key:
    v0-rust-x86_64-unknown-linux-gnu-unused-dependencies-check-1.56.0-nightly-x86_64-unknown-linux-gnu-2d2bc94c8c3a-1f638b2bd5788a73a101
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/fluvio/fluvio --files-from manifest.txt
Cache Size: ~465 MB (487138769 B)
Cache saved successfully
```

However, in the rust-cache README, they give note about their [cache effectiveness](https://github.com/Swatinem/rust-cache#cache-effectiveness).

```
Usage with Stable Rust is most effective, as a cache is tied to the Rust version. Using it with Nightly Rust is less effective as it will throw away the cache every day.
```

I think this means that we're just going to have a slower first build every day.

---

We can either accept that as `cargo-udeps` requires running in nightly, or one alternative is we might push this test to run only when we're merging to `master`?

2021-09-30 21:00 UTC, sehz commented
Do we still need this?

2021-09-30 23:08 UTC, tjtelan commented
> Do we still need this?

Maybe, if we're accepting #415 as valid enough to include in CI. Otherwise we should close it.

We left off on the question as to whether this check is worth the minutes is takes to run?

It's worst-case runtime will always be the first builds of the day, because `rust-cache` performs poorly on `nightly` (a current requirement of `check-udeps`)

---

Personally, I think it would be ok to include. Without a cache-hit, it isn't the longest running check. So I don't expect that it will result in longer builds.

If you agree, I can rebase this.

2022-02-01 02:51 UTC, sehz requested changes

2022-02-01 02:51 UTC, sehz commented on .github/workflows/ci_unused_deps.yml
> +  group: ${{ github.head_ref || 'ci_unused_deps' }}
this needs to be in terms of `dep-check-${{ github.ref }}` or something like that.

2022-02-01 02:51 UTC, sehz commented on .github/workflows/ci_unused_deps.yml
> +    branches: [master]
I think this needs to be run only in staging

2022-02-04 20:00 UTC, morenol commented on .github/workflows/stale.yml
>  jobs:
I think that the changes on this file should not be in this PR

2022-02-07 20:00 UTC, morenol requested changes

2022-02-07 20:00 UTC, morenol commented on makefiles/check.mk
> +check-udeps: install-udeps
there are some conflicts on this file

2022-02-07 22:38 UTC, morenol approved these changes

2022-02-09 19:45 UTC, morenol commented
@tjtelan  this PR has conflicts in Cargo.lock

2022-02-09 21:25 UTC, tjtelan commented
> @tjtelan this PR has conflicts in Cargo.lock

conflict is now fixed

2022-02-09 21:28 UTC, sehz approved these changes
LGTM.  Great

2022-02-09 21:29 UTC, sehz commented
bors r+

2022-02-09 22:02 UTC, sehz commented
bors r+

2022-02-09 22:43 UTC, tjtelan commented
bors r+

2022-02-09 23:05 UTC, closed without merging