Create SmartStreamBase to manage wasmtime/memory
infinyon/fluvio pull request #1552
Opened 2021-09-01 22:23 UTC by nicholastmosher

This pulls a lot of the `wasmtime` code related to reading and writing memory into a common type called `SmartStreamBase`. Each concrete smartstream wraps this as well as their own typed wasm function and potentially any state (e.g. the aggregate accumulator).

This is part 1 of the smartstreams refactor in preparation for #1335

2021-09-01 22:39 UTC, sehz requested changes
Looks good.  1 minor point

2021-09-01 23:03 UTC, nicholastmosher commented
@sehz what's the minor point? 😂

2021-09-01 23:07 UTC, sehz commented on crates/fluvio-spu/src/smartstream/mod.rs
> +pub struct SmartStreamBase {
Somehow.  my comment got lost.
Let's have more descriptive name than `SmartStreamBase`.  `SmartStreamRecordContext`, `SmartStreamInstance`....

2021-09-02 02:13 UTC, nicholastmosher commented on crates/fluvio-spu/src/smartstream/mod.rs
> +pub struct SmartStreamBase {
How about just `SmartStreamContext`?

2021-09-02 02:43 UTC, sehz approved these changes
LGTM

2021-09-02 02:43 UTC, sehz commented
bors r+

2021-09-02 03:16 UTC, sehz commented
bors r+

2021-09-02 03:30 UTC, closed without merging