Delete unused modules in fluvio-sc
infinyon/fluvio pull request #1597
Opened 2021-09-10 21:56 UTC by nicholastmosher

All of these modules in `fluvio-sc` were completely unused, i.e. they were not linked in the module tree and deleting them has no effect on the project. Let me know if any of this should be saved, but if not I think it's a good cleanup.

2021-09-10 23:00 UTC, sehz requested changes

2021-09-13 12:21 UTC, nicholastmosher commented on crates/fluvio-sc/src/tests/TESTS.md
> -* After while, 2nd SPU's status should be offline since we didn't bring up 2nd SPU yet
It was in a directory where everything else was unused and got deleted, so I figured it was no longer relevant.

2021-09-13 15:27 UTC, sehz commented on crates/fluvio-sc/src/tests/TESTS.md
> -* After while, 2nd SPU's status should be offline since we didn't bring up 2nd SPU yet
this needs to be kept

2021-09-13 17:48 UTC, nicholastmosher commented on crates/fluvio-sc/src/tests/TESTS.md
> -* After while, 2nd SPU's status should be offline since we didn't bring up 2nd SPU yet
Ok, this file is no longer deleted in this PR

2021-09-13 18:32 UTC, sehz approved these changes

2021-09-13 18:33 UTC, nicholastmosher commented
bors r+

2021-09-13 18:53 UTC, closed without merging