Add 'fluvio diagnostics' for collecting debug information
infinyon/fluvio pull request #1671
Opened 2021-09-21 18:07 UTC by nicholastmosher

Closes #1667 and #1215

Adds `fluvio diagnostics` subcommand which will produce a zip file, `diagnostics-YYYY-MM-DD-hh-mm-ss.zip`. This file contains:

- Logs for any SC or SPU, local or kubernetes
- Kubernetes metadata, including all Fluvio pods/services/statefulsets, and CRD's spu/spg/partition/topic
- Fluvio admin metadata, topic/partition/spu/spg

2021-09-21 20:05 UTC, sehz commented
I noticed that it is using zip format.  This should be in `.gz` format as they are unix standard

2021-09-21 20:21 UTC, sehz requested changes
* add to change log.
* need to add k8 PVC objects

2021-09-21 20:21 UTC, sehz commented on crates/fluvio-cluster/src/cli/diagnostics.rs
> +const LOGS_PATH: &str = "/usr/local/var/log/fluvio/";
should be using same path from cluster config not duplicating it

2021-09-21 20:21 UTC, sehz commented on crates/fluvio-cluster/src/cli/error.rs
> +    Which(#[from] which::Error),
This goes into diagnostics error or turn into io error

2021-09-22 15:19 UTC, nicholastmosher commented
@sehz this should be ready to go. Now uses `.tar.gz` instead of `.zip`, and extracts into a `./diagnostics/` directory.

2021-09-22 15:57 UTC, sehz approved these changes
Excellent!  this will make it easier to collect debugging info fluvio

2021-09-22 15:57 UTC, sehz commented
bors r+

2021-09-22 16:29 UTC, sehz commented
clippy failures

2021-09-22 16:39 UTC, nicholastmosher commented
bors r+

2021-09-22 16:57 UTC, closed without merging