Report error to client when SPU is given invalid WASM module
infinyon/fluvio pull request #1713
Opened 2021-10-01 19:45 UTC by nicholastmosher

Closes #1143.

When supplying an invalid WASM module to the consumer, the client will now return with the following error:

```
$ flvd consume fruits -B --filter=Cargo.toml          # note that Cargo.toml is not a valid WASM file
Consuming records starting 10 from the end of topic 'fruits'
Error:
   0: Fluvio client error
   1: SmartStream error
   2: WASM Module error: failed to parse WebAssembly module
```

Action items:

- [x] Implement error delivery
- [ ] Add integration test

2021-10-01 20:24 UTC, sehz requested changes
Looks good.  Just couple of nits

2021-10-01 20:24 UTC, sehz commented on crates/fluvio-dataplane-protocol/src/error_code.rs
> +    Module(String),
Should be more explicit, something like `InvalidWASMModule`

2021-10-01 20:24 UTC, sehz commented on crates/fluvio-spu/src/services/public/stream_fetch.rs
> +            let module = match module_result {
these 2 lines can collapse

2021-10-01 21:55 UTC, sehz approved these changes
LGTM

2021-10-01 21:55 UTC, sehz commented
bors r+

2021-10-02 12:45 UTC, nicholastmosher commented
Oh interesting, I didn't actually know what the crate_version check did until now! Cool catch, and nice script @tjtelan!

bors r+

2021-10-02 12:56 UTC, closed without merging