Add consumer output type full_table
infinyon/fluvio pull request #1860
Opened 2021-11-07 02:55 UTC by tjtelan

Attempt 2 for #1846

We're leaving `--output=table` intact and adding full screen table render at `--output=full_table`

2021-11-07 18:24 UTC, sehz requested changes
Overall look good. Just need remove panic and expect

2021-11-07 18:24 UTC, sehz commented on crates/fluvio-cli/src/consume/record_format.rs
> +        table.print(&mut out).expect("Unable to print table");
remove expect

2021-11-07 18:24 UTC, sehz commented on crates/fluvio-cli/src/consume/record_format.rs
> +        slice.print(&mut out).expect("Unable to print row");
remove expect

2021-11-07 18:24 UTC, sehz commented on crates/fluvio-cli/src/consume/record_format.rs
> +            disable_raw_mode().expect("Disabling raw mode failed");
remove expect

2021-11-07 18:24 UTC, sehz commented on crates/fluvio-cli/src/consume/record_format.rs
> +            .expect("Failed to leave alternate screen");
remove expect

2021-11-07 18:24 UTC, sehz commented on crates/fluvio-cli/src/consume/record_format.rs
> +            terminal.show_cursor().expect("Show terminal cursor failed");
remove expect

2021-11-07 18:24 UTC, sehz commented on crates/fluvio-cli/src/consume/record_format.rs
> +            panic!("Value not json")
convert to proper error

2021-11-07 18:24 UTC, sehz commented on crates/fluvio-cli/src/consume/record_format.rs
> +    let obj = maybe_json.as_object().unwrap();
return error

2021-11-07 18:24 UTC, sehz commented on crates/fluvio-cli/src/consume/record_format.rs
> +                    .expect("Value not representable as str")
remove expect

2021-11-07 18:24 UTC, sehz commented on crates/fluvio-cli/src/consume/record_format.rs
> +        .expect("Unable to set table headers");
remove expect

2021-11-07 18:24 UTC, sehz commented on crates/fluvio-cli/src/consume/record_format.rs
> +        .expect("Unable to update table row");
remove expect

2021-11-07 18:24 UTC, sehz commented on crates/fluvio-cli/src/consume/table_format.rs
> +            .expect("Could not render table frame");
remove expect

2021-11-07 18:28 UTC, sehz commented
invalid json leads to panic: ```flvd consume test2 -B --output table
Consuming records from the beginning of topic 'test2'
The application panicked (crashed).
Message:  Value not json
Location: crates/fluvio-cli/src/consume/record_format.rs:94```

this should be handle gracefully.

2021-11-07 18:34 UTC, sehz commented
Issues in display
* Terminal doesn't seems to take entire view
* Scrolling doesn't work

2021-11-07 21:27 UTC, tjtelan commented
> Issues in display
> 
>     * Terminal doesn't seems to take entire view
> 
>     * Scrolling doesn't work

Both of these issues are not present in Linux.

Testing on MacOS, I can repro these issues. Might need to play around with the different terminal backends, but I chose `crossterm` since it was supposed to support all the basic unix and Windows.

2021-11-07 21:36 UTC, sehz commented
Can you try different backends?

2021-11-08 02:26 UTC, tjtelan commented
Tried swapping backend from `crossterm` to `termion` and tested on my local macos box. It seems to clear the screen and draw the table correctly for the first frame. If you press any button it exits, and the table doesn't update.

On Linux, I don't even notice a change. It works with both crossterm and termion.

2021-11-08 06:00 UTC, tjtelan commented
I reverted the Termion commit after playing around with Crossterm on MacOS more. I get fullscreen tables that update, clear screen and exit cleanly. There seems to be more of an issue with the stability around redrawing frames if the data isn't updating.

Here's a screenshot from MacOS with the selection active, and immediately after clearing the screen. The output feels much more sluggish than on my Linux dev environment, but it does work with the keyboard and mouse inputs.

<img width="782" alt="image" src="https://user-images.githubusercontent.com/344960/140691691-7058fd07-7398-471f-a70e-5bc9e79af587.png">

2021-11-08 15:49 UTC, sehz commented
Same problem on MacOS (VsCode, Terminal emulator, Alacrity).
- "C" command didn't work
- Scroll still doesn't work,

Code looks good so let's merge and fix these issues.

2021-11-08 15:49 UTC, sehz approved these changes
LGTM

2021-11-08 15:49 UTC, sehz commented
bors r+

2021-11-08 16:06 UTC, closed without merging