Csb 1850
infinyon/fluvio pull request #1939
Opened 2021-11-24 17:51 UTC by bohlmannc

# What does this PR do?

This PR exposes fluvio completions in the top-level subcommand by removing the hidden AppSettings.
 
# Motivation

I wanted to tackle a good first issue and make my first open source contribution.

# Related issues

A list of issues closed by or relevant to this PR.

- Closes [#1850] (https://github.com/infinyon/fluvio/issues/1850).

# Additional Notes

Is there anything else you'd like us to know while reviewing this?

# Checklist

- [x] Created or updated all relevant documentation
- [ ] Added unit tests to relevant added or changed code
- [ ] Bumped required crate version numbers
- [x] Updated CHANGELOG.md

2021-11-24 17:57 UTC, simlay commented
I know it's out of scope of this PR but if you're up for it, looking if [`fluvio completions zsh` still panics](https://github.com/infinyon/fluvio/blob/513f6b29b9ac4f610001b4b961659a00f1fc4e8b/crates/fluvio-cli/src/lib.rs#L331-L335) would be very nice. It might be blocked on https://github.com/TeXitoi/structopt/issues/124

2021-11-24 18:10 UTC, sehz commented
> I know it's out of scope of this PR but if you're up for it, looking if [`fluvio completions zsh` still panics](https://github.com/infinyon/fluvio/blob/513f6b29b9ac4f610001b4b961659a00f1fc4e8b/crates/fluvio-cli/src/lib.rs#L331-L335) would be very nice. It might be blocked on [TeXitoi/structopt#124](https://github.com/TeXitoi/structopt/issues/124)

Let's do that in separate PR.

2021-11-24 18:18 UTC, sehz commented
Please link to issue

2021-11-24 20:17 UTC, sehz commented
CI failure: https://github.com/infinyon/fluvio/actions/runs/1500562059

2021-11-24 22:59 UTC, sehz requested changes
Seems like help comments are not properly break down into multiple lines
```
$ flvd completions
fluvio-completions 0.0.0
Generate command-line completions for Fluvio Run the following two commands to enable fluvio
completions. fluvio completions bash > ~/fluvio_completions.sh echo "source ~/fluvio_completions.sh"
>> ~/.bashrc Open a new terminal for changes to take effect

USAGE:
    fluvio completions <SUBCOMMAND>

FLAGS:
    -h, --help    Prints help information

SUBCOMMANDS:
    bash    Generate CLI completions for bash
    fish    Generate CLI completions for fish
    help    Prints this message or the help of the given subcommand(s)
```

Take look at structopt: https://docs.rs/structopt/0.3.25/structopt/#magical-methods.

2021-11-24 23:04 UTC, sehz commented
Otherwise works on Linux and Mac!

2021-11-25 01:23 UTC, bohlmannc commented
<img width="1440" alt="Screen Shot 2021-11-24 at 8 19 54 PM" src="https://user-images.githubusercontent.com/44445083/143335868-265f72c7-bfd6-4384-8b16-8f0f2f6146ba.png">


-----------
So I fixed the file, ran `flvd completions` and could see improved formatting in the terminal. But when I run `make check-fmt`, it says there are extra lines with `///`. Is there something going on with check-fmt? Sorry for small font but was trying to capture everything as an earlier build failed on check-fmt with the same error as well.

2021-11-25 01:28 UTC, sehz commented
what's error from `make check-fmt`?.  You might need to put line separator.  Or can skip `fmt` check.

2021-11-25 01:54 UTC, sehz commented
There is now extra line instead:
```
$ flvd completions
fluvio-completions 0.0.0
Generate command-line completions for Fluvio

Run the following two commands to enable fluvio command completions. Open a new terminal for the
changes to take effect.

$ fluvio completions bash > ~/fluvio_completions.sh

$ echo "source ~/fluvio_completions.sh" >> ~/.bashrc
```

2021-11-25 04:33 UTC, sehz approved these changes
Looks good. Thanks

2021-11-25 04:33 UTC, sehz commented
bors r+

2021-11-25 05:05 UTC, closed without merging