Introduce channels into CLI
infinyon/fluvio pull request #2021
Opened 2021-12-15 01:06 UTC by tjtelan

This adds the concept of separate `channels` in the CLI, with the ability to change between them. (This is on by default, but channel checks can be skipped with `fluvio --skip-channel-check <subcommand>`)

3 possible channels:
* `stable`
* `latest`
* `dev`

By default, we use the `stable` channel, but you can switch to another channel with:

`fluvio config --set-channel <channel>`

---

Simplifies starting a cluster to `fluvio cluster start` for all channels

Resolves #1663

2021-12-16 02:20 UTC, tjtelan commented
Looks like CLI works on `dev` channel. Need to do some testing to make sure `stable` and `latest` channels work as expected

2021-12-22 17:00 UTC, sehz requested changes
First pass:

Just several minor nits.

2021-12-22 17:36 UTC, sehz requested changes
The major question is why this can't be in a separate crate?

2021-12-22 17:36 UTC, sehz commented on crates/fluvio-cli/src/derivedstream/describe.rs
> +#[derive(Debug, StructOpt, Clone)]
why this need to be cloned?

2021-12-22 21:13 UTC, tjtelan commented
Based on feedback, I'll be moving the `fluvio-channel` binary into its own crate.

Also I'm going to experiment with minimizing the channel selection logic in `fluvio` cli using environment variables that `fluvio-channel` will set. (Definitely leverage structopt to add this support into `fluvio`)

2021-12-29 22:18 UTC, sehz approved these changes
Looks great.  Nice Job!

2021-12-29 22:38 UTC, sehz commented
rebase

2021-12-30 03:11 UTC, sehz commented
bors r+

2021-12-30 03:36 UTC, sehz commented
bors r+

2021-12-30 04:04 UTC, sehz commented
bors r+

2021-12-30 08:01 UTC, sehz commented
zig issue is fixed.  can you rebase?

2021-12-30 15:44 UTC, sehz commented
bors r+

2021-12-30 16:01 UTC, sehz commented
bors r+

2021-12-30 16:22 UTC, sehz commented
bors r+

2021-12-30 17:43 UTC, sehz commented
bors r+

2021-12-30 17:51 UTC, sehz requested changes

2021-12-30 17:51 UTC, sehz commented on .github/workflows/ci.yml
> +          - os: macos-latest
this need to use `macos-11` with zig related changes

2021-12-30 17:53 UTC, sehz commented
windows build fails in staging:
```
   --> crates/fluvio-dataplane-protocol/src/record.rs:690:24
776
    |
777
690 |     use fluvio_future::file_slice::AsyncFileSlice;
778
    |                        ^^^^^^^^^^ could not find `file_slice` in `fluvio_future`
```

2021-12-31 06:19 UTC, sehz commented
bors r+

2021-12-31 06:37 UTC, closed without merging