Add retention to ci artifacts
infinyon/fluvio pull request #2153
Opened 2022-02-01 02:31 UTC by tjtelan

All build-related artifacts have 1 day retention
Fixes #2139

2022-02-04 19:53 UTC, morenol approved these changes

2022-02-04 19:58 UTC, tjtelan commented
Based on standup feedback, moving retention to 7 days

2022-02-04 22:18 UTC, morenol approved these changes

2022-02-06 21:18 UTC, sehz requested changes

2022-02-06 21:18 UTC, sehz commented on .github/workflows/ci.yml
> +          retention-days: 7
We can set this to 1 day

2022-02-07 19:47 UTC, morenol approved these changes

2022-02-09 19:34 UTC, sehz approved these changes

2022-02-09 19:34 UTC, sehz commented
bors r+

2022-02-09 19:58 UTC, closed without merging