Resolve issue_2168 with regression test
infinyon/fluvio pull request #2170
Opened 2022-02-09 11:14 UTC by rrrodzilla

- add: dev dependencies predicates, assert_cmd, rand
- fix: issue_2168

2022-02-09 17:56 UTC, sehz commented
@tjtelan Can you review this PR?

2022-02-09 22:17 UTC, tjtelan requested changes
I needed to change one line in `fluvio-channel-cli`'s `Cargo.toml` to get the test to compile. Could you make that change please?

```diff
- fluvio-cli-common = { path = "../fluvio-cli-common", default-features = false }
+ fluvio-cli-common = { path = "../fluvio-cli-common"}
```

Also, thanks for writing a test! Could you add this test to [this makefile, in the `run-all-unit-test` target](https://github.com/rrrodzilla/fluvio/blob/7137d22309b50e998e5b2a153f6fccf8911818b3/makefiles/check.mk#L28) so we can run it during CI?

```diff
+ cargo test -p fluvio-channel-cli $(BUILD_FLAGS)
```

Otherwise I manually tested and it fixes issue #2168 ✅

LGTM!

2022-02-09 22:27 UTC, rrrodzilla commented
Hey thanks for having a review.  I've made the requested changes with this last commit.  Thanks again!

2022-02-09 22:29 UTC, sehz requested changes

2022-02-09 22:29 UTC, sehz commented on crates/fluvio-channel-cli/tests/issue_2168_regression.rs
> +    let mut cmd = Command::cargo_bin("fluvio-channel")?;
same here

2022-02-09 22:35 UTC, rrrodzilla commented
Updates to the test with the requested changes pushed!

2022-02-09 22:42 UTC, rrrodzilla reviewed
I've updated the test to handle errors internally with `expect`

2022-02-09 22:44 UTC, sehz approved these changes

2022-02-09 23:28 UTC, sehz commented
There is test failure: https://github.com/infinyon/fluvio/runs/5133172297?check_suite_focus=true

2022-02-09 23:56 UTC, rrrodzilla commented
@tjtelan The test running from the makefile is expecting a channel config file in the CI environment and it's not finding one.  Is there not one or should I expect it in a different location?

2022-02-10 00:25 UTC, tjtelan commented
> @tjtelan The test running from the makefile is expecting a channel config file in the CI environment and it's not finding one. Is there not one or should I expect it in a different location?

Yeah, the CI environment wouldn't have a channel file because we are only using the standard github runners. You'll need to create the config file when in the CI environment before running the test.

You can do a CI check by looking for the [`CI` environment variable](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables), which Github Actions will always set to `true`.

If that env var exists and it is set to `true`, you can run `fluvio-channel version switch stable`. I just tested locally, and it will create the `~/.fluvio` directory and the `channel` config for the rest of the test to use.

2022-02-10 03:02 UTC, tjtelan approved these changes

2022-02-10 03:04 UTC, sehz commented
Good job.  Thanks for contribution!

2022-02-10 03:04 UTC, sehz commented
bors r+

2022-02-10 03:39 UTC, closed without merging