disable fluvio update command when using version channel
infinyon/fluvio pull request #2184
Opened 2022-02-11 00:50 UTC by LanceEa

This closes #2155 by checking the channel config to see if the active channel is a pinned version channel. If channel is pinned to a version then `fluvio update` is not supported.

2022-02-11 01:38 UTC, sehz commented
@tjtelan please review

2022-02-11 04:47 UTC, tjtelan requested changes

2022-02-11 22:10 UTC, LanceEa commented on crates/fluvio-cli/src/lib.rs
> +                    }
@tjtelan  - ahh makes sense 👍. 

I thought `fluvio-cli` was calling into `fluvio-channel-cli` but I see based on the `install.sh` script that the `fluvio-channel` is getting renamed to `fluvio`. Then all non-channel commands are being forwarded to the `fluvio-cli` binaries (fluvio-stable, fluvio-0.9.18, etc...).

I will get that fixed up over the weekend.

2022-02-13 20:13 UTC, LanceEa commented
@tjtelan  - I have moved the logic into `fluvio-channel-cli` and fixed up the tests. Let me know if this aligns more with what you were thinking.

2022-02-15 21:34 UTC, tjtelan approved these changes
Local test works

LGTM

2022-02-15 21:40 UTC, tjtelan commented
Please add to CHANGELOG.md https://github.com/infinyon/fluvio/blob/master/CHANGELOG.md and fix the failing Clippy test before merge

2022-02-16 19:08 UTC, tjtelan commented
bors r+

2022-02-16 19:33 UTC, tjtelan commented
bors r+

2022-02-16 19:53 UTC, tjtelan commented
bors r+

2022-02-16 20:26 UTC, tjtelan commented
That last merge attempt failure was on Github Actions. All the other jobs passed. :face_with_head_bandage:

![image](https://user-images.githubusercontent.com/344960/154351081-866f75c7-9393-4be3-8e16-5721c57f4b4b.png)

2022-02-16 20:26 UTC, tjtelan commented
bors r+

2022-02-16 20:44 UTC, closed without merging