[Merged by Bors] - Add fish support to install.sh
infinyon/fluvio pull request #2389
Opened 2022-05-18 15:47 UTC by joshchngs

I recently installed Fluvio from the online installer, but I felt left out when it came time to adding the bindir to my path.

The first commit is the important one, the others just clean the output up slightly, now there are 3 variants.

2022-05-18 15:57 UTC, sehz commented
Thanks for contribution

2022-05-19 02:22 UTC, tjtelan requested changes
This works as expected using `bash` and `zsh`, but it doesn't seem to work at all with `fish`.

In each of my examples, the user has the variant shell set as their login, to ensure the `$SHELL` var is set correctly. This should always return the same value even if you were to pipe the script to a different shell. 

bash
```
bashy@2ad9c674bbea:~$ echo $SHELL
/bin/bash
bashy@2ad9c674bbea:~$ cat install.sh | bash
[...]
fluvio:       echo 'export PATH="${HOME}/.fluvio/bin:${PATH}"' >> ~/.bashrc
```

zsh
```
2ad9c674bbea% echo $SHELL
/usr/bin/zsh
2ad9c674bbea% cat install.sh|zsh
[...]
fluvio:       echo 'export PATH="${HOME}/.fluvio/bin:${PATH}"' >> ~/.zshrc
```

For me, the script has an error if I try to execute w/ `fish`
```
fishy@2ad9c674bbea ~> echo $SHELL
/usr/bin/fish

fishy@2ad9c674bbea ~> cat install.sh | fish
fish: Unexpected ')' found, expecting '}'
        x86_64-unknown-linux-gnu)
                                ^
```

This would print `fish_hint`, but there's a little typo.

```
fishy@2ad9c674bbea ~ [0|127]> cat install.sh | bash
[...]
fluvio:       echo 'export PATH="${HOME}/.fluvio/bin:${PATH}"' >> ~/.bashrc

fishy@2ad9c674bbea ~> cat install.sh | zsh
[...]
fluvio:       echo 'export PATH="${HOME}/.fluvio/bin:${PATH}"' >> ~/.bashrc
```

When I changed L159 to `fish_hint`, this does print correctly, however. 

```
fishy@2ad9c674bbea ~> cat install.sh | zsh
[...]
fluvio:       fish_add_path "$HOME/.fluvio/bin"
```

2022-05-19 02:22 UTC, tjtelan commented on install.sh
> +            say "      ${bash_hint}"
Typo: `fish_hint`

2022-05-19 08:01 UTC, joshchngs commented on install.sh
> +            say "      ${bash_hint}"
Oops! That's from testing - fixed.

2022-05-19 08:04 UTC, joshchngs commented
This isn't intended to execute under `fish` - that wouldn't work. The install flow should stay the same - `curl | bash`.

The change is just that the PATH-setting instructions are emitted differently. Here's how it looks for me (on fish):
<img width="930" alt="Screenshot 2022-05-19 at 09 04 12" src="https://user-images.githubusercontent.com/16120047/169244106-1db2d8e4-0a84-4d70-a8dd-ce20f8a3f560.png">
:

2022-05-19 17:54 UTC, tjtelan approved these changes

2022-05-19 20:23 UTC, sehz commented
can you add to changelog?

2022-05-19 20:26 UTC, joshchngs commented
Sure. I didn't make an issue like the other entries - just link to this PR?

2022-05-19 20:38 UTC, sehz approved these changes
Great.  thanks

2022-05-19 20:38 UTC, sehz commented
bors r+

2022-05-20 03:46 UTC, sehz commented
bors r+

2022-05-20 04:15 UTC, closed without merging