[Merged by Bors] - Add specific log_dir creation error
infinyon/fluvio pull request #2425
Opened 2022-06-20 10:03 UTC by joshchngs

Previous implementation simply prints:
	0: Fluvio cluster error
	1: Permission denied (os error 13)

...which gives no information regarding which operation caused the
error, or even to which path the error relates.

This commit adds an interstitial error to the chain, which prints:
	1: An error occurred creating the cluster log directory "/usr/local/var/log/fluvio"

2022-06-20 10:30 UTC, joshchngs commented
@nicholastmosher I hit this issue because my user doesn't have any write permissions inside `/usr/local`.
I'm on Apple Silicon, MacOS 12.4.

I don't have a quick way to confirm with a fresh install, but I *think* this is the new default permission set on arm64.
Question: what's the reason for the different default log_dir under macos, and is it still valid?

2022-06-22 17:58 UTC, tjtelan requested changes
> I don't have a quick way to confirm with a fresh install, but I _think_ this is the new default permission set on arm64.

@joshchngs Is there any way you can write a simple test that uses the CLI to throw the error and validates your error message matches what you set? 

Please add it to [the Mac CI](https://github.com/infinyon/fluvio/blob/master/.github/workflows/ci_mac.yaml). This is a filesystem permissions issue, not specifically a MacOS related issue. But it will be the easiest area for you to add CLI tests against a local cluster.

Copy this job as a base for your local CLI test

https://github.com/infinyon/fluvio/blob/477b2609a68cfa728a2fab661665e98efefe132b/.github/workflows/ci_mac.yaml#L121

Replace the job name, modify the job to set your test conditions and run your test
https://github.com/infinyon/fluvio/blob/477b2609a68cfa728a2fab661665e98efefe132b/.github/workflows/ci_mac.yaml#L175-L179

2022-06-27 13:29 UTC, joshchngs commented
That's done. It's a fairly trivial test which comes with 10 minutes of boilerplate docker/k8s setup. I'd suggest rolling it into the  existing local cluster setup as an additional step if the overhead becomes a problem.

2022-06-27 14:17 UTC, joshchngs commented
Alright, that's ready to merge from my end. Pushed a CI test for the default case, which seems OK on the x86_64 macos-12 runner, so I unpushed that commit. So, either something else changed `/usr` permissions on my setup or it's actually different on arm64. At least if somebody else hits it there is a more informative error.

2022-06-27 22:44 UTC, tjtelan requested changes
One last ask before merge: Can you add a reference to this fix in [`CHANGELOG.md`](https://github.com/infinyon/fluvio/blob/master/CHANGELOG.md)?

Otherwise, LGTM, thanks!

2022-06-27 23:24 UTC, joshchngs commented
Done  - against 0.9.30 (rebased on master)

2022-06-27 23:28 UTC, tjtelan approved these changes

2022-06-28 00:47 UTC, sehz commented
see https://stackoverflow.com/questions/16432071/how-to-fix-homebrew-permissions

2022-06-28 00:49 UTC, sehz commented
For homebrew users, we didn't encounter this issue since we probably fix the permission problem a long time ago and totally forgotten about it.

2022-06-28 01:34 UTC, sehz commented
bors r+

2022-06-28 02:02 UTC, closed without merging