[Merged by Bors] - Make version required in connector yaml
infinyon/fluvio pull request #2472
Opened 2022-07-12 16:39 UTC by simlay

Closes #2456.

2022-07-12 17:08 UTC, ajhunyady commented
Is this change backward compatible?

2022-07-12 17:13 UTC, simlay commented
> Is this change backward compatible?

Yes.

2022-07-12 17:39 UTC, sehz requested changes
is there a negative test? if required version is missing, it should fail

2022-07-12 17:48 UTC, sehz approved these changes
LGTM

2022-07-12 17:58 UTC, morenol commented on crates/fluvio-controlplane-metadata/src/connector/spec.rs
> +            ConnectorVersionInner::Option(inner) => inner.clone().unwrap_or_else(|| "".to_string()),
this is for the old connectors right? shouldn't it be `latest` by default?

Not sure what is the expected response to `fluvio connector config old-connector` when it was created with the previos version.

2022-07-12 18:15 UTC, morenol commented on crates/fluvio-sc-schema/src/objects/list.rs
> +    const DEFAULT_API_VERSION: i16 = 9;
Probably we want to update this also for `watch.rs` so we don't have problems when we do the Update controller

2022-07-12 18:48 UTC, morenol approved these changes
looks good to me!

2022-07-12 21:32 UTC, simlay commented
bors r+

2022-07-12 23:50 UTC, simlay commented
bors retry

2022-07-13 00:53 UTC, tjtelan commented
bors retry

2022-07-13 01:05 UTC, tjtelan commented
@simlay

The reason Bors can't merge because fluvio check test is failing.
https://github.com/infinyon/fluvio/runs/7312057421?check_suite_focus=true

2022-07-13 01:09 UTC, simlay commented
@bors retry

2022-07-13 02:27 UTC, tjtelan commented
bors r+

2022-07-13 02:56 UTC, simlay commented
bors retry

2022-07-13 03:16 UTC, sehz commented
bors r+

2022-07-13 03:33 UTC, closed without merging