improve error messages
infinyon/fluvio pull request #2563
Opened 2022-08-16 18:17 UTC by gregwebs

I was messing around with the initialization of Fluvio and improving these error messages helped me understand what was going on. Also just noticed a typo in an error message.

2022-08-16 18:58 UTC, tjtelan requested changes
This looks good, but CI has some failures. It looks like CI code formatting checks failed, but I expect that crate version checks will also fail.

Can you run `cargo fmt` for the formatting check, and bump the patch version of the publishable crates?

2022-08-16 19:06 UTC, sehz requested changes
Thanks for PR.  LGTM.  One minor nit

2022-08-16 20:42 UTC, gregwebs commented on crates/fluvio-spu/src/config/cli.rs
> +                format!("SPU index id not found form SPU_INDEX or {FLV_SPU_ID}")
oh, yes! PR is updated now.

2022-08-16 20:44 UTC, gregwebs commented
I ran `cargo fmt`.

> and bump the patch version of the publishable crates

Oh, is there some automation to help with that?

2022-08-16 21:44 UTC, tjtelan commented
> I ran `cargo fmt`.
> 
> > and bump the patch version of the publishable crates
> 
> Oh, is there some automation to help with that?

There isn't, but [it looks like the test passed](https://github.com/infinyon/fluvio/runs/7866880300?check_suite_focus=true), so there's nothing you need to do. (Someone recently updated these crates too, so they updated the versions for next release.)

However, it looks like the [clippy](https://github.com/infinyon/fluvio/runs/7866879840?check_suite_focus=true) test failed

2022-08-17 04:18 UTC, tjtelan approved these changes

2022-08-17 16:08 UTC, sehz approved these changes
LGTM.  Thanks for cleanup

2022-08-17 16:08 UTC, sehz commented
bors r+

2022-08-17 18:10 UTC, sehz commented
bors r+

2022-08-17 18:47 UTC, closed without merging