fix: provide keys for yaml example
infinyon/fluvio pull request #2611
Opened 2022-09-14 20:51 UTC by EstebanBorai

Following who Fluvio is run locally, I have found that Kubernetes
config is missing the section keys as shown in [this documentation][1]
section. Other fields like `apiVersion` are omitted to avoid conflicts with
version mismatch.

[1]: https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#proxy

2022-09-18 18:33 UTC, sehz commented
Thanks for PR

2022-09-18 18:34 UTC, sehz commented
@nacardin Can you review this?

2022-09-22 15:40 UTC, nacardin requested changes

2022-09-23 14:30 UTC, EstebanBorai commented on k8-util/DEVELOP.md
> +kubectl proxy
Roger!

2022-09-23 18:20 UTC, nacardin approved these changes

2022-09-23 20:39 UTC, sehz commented
bors r+

2022-09-23 21:03 UTC, closed without merging