ci: Updates to release for SmartModule Development Kit
infinyon/fluvio pull request #2648
Opened 2022-10-05 02:33 UTC by tjtelan

Related #2644 

Added `smdk` to CI for build and publish for CI

Moving a lot of publish and release workflows into Makefile so I can test it easier locally

2022-10-06 18:54 UTC, sehz requested changes
Looks very good.  One minor not about naming

2022-10-06 18:54 UTC, sehz commented on crates/smart-module-development-kit/Cargo.toml
> +name = "smart-module-development-kit"
Let's change to `smartmodule-development-kit`.   
We should change other smarmodule crates as well.

2022-10-06 23:03 UTC, sehz approved these changes
LGTM

2022-10-07 15:52 UTC, sehz commented
bors r+

2022-10-07 16:58 UTC, tjtelan commented
Bors failed because while we had steps to upload SMDK in CI, but we weren't building it in the first place. Hopefully this will fix.

bors r+

2022-10-07 17:32 UTC, tjtelan commented
Based on cranelift-codegen's build, I removed the arm and arm7 targets. I hope this build is the one!

https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/codegen/build.rs#L174

bors r+

2022-10-07 18:34 UTC, tjtelan commented
bors r+

2022-10-07 18:42 UTC, tjtelan commented
bors r+

2022-10-07 19:56 UTC, tjtelan commented
This time it was publish to Github Release (`dev`) that failed. I checked on the Publish, and Release workflows to ensure that we don't have this kind of artifact missing traps waiting for us there.

bors r+

2022-10-07 21:08 UTC, tjtelan commented
bors r+

2022-10-07 21:42 UTC, tjtelan commented
I really wish Bors supported rerunning jobs...

bors r+

2022-10-07 22:38 UTC, tjtelan commented
I had to rebase after the last PR, but here we go again

bors r+

2022-10-07 23:17 UTC, tjtelan commented
Removed Windows targets for `smdk` for now

bors r+

2022-10-07 23:47 UTC, closed without merging