[Merged by Bors] - feat: add fluvio hub util
infinyon/fluvio pull request #2649
Opened 2022-10-05 15:57 UTC by digikata

2022-10-05 19:10 UTC, sehz requested changes
first sets of comments

2022-10-05 19:10 UTC, sehz commented on crates/fluvio-hub-util/src/lib.rs
> +pub const HUB_BUCKET: &str = "devel-hub";
remove BUCKET REF

2022-10-06 00:25 UTC, digikata commented on crates/fluvio-hub-util/Cargo.toml
> +env_logger = "*"
nope, removed

2022-10-06 00:26 UTC, digikata commented on crates/fluvio-hub-util/Cargo.toml
> +name = "fluvio-hub-util"
fluvio-hub-util handles smartmodule packages, but doesn't have to be only smartmodules. Maybe we should keep the name more general for now?

2022-10-06 00:27 UTC, digikata commented on crates/fluvio-hub-util/Cargo.toml
> +version = "0.3.15"
I just removed all the dev dependencies as they weren't necessary.

2022-10-06 01:50 UTC, sehz commented on crates/fluvio-hub-util/Cargo.toml
> +name = "fluvio-hub-util"
k

2022-10-06 22:08 UTC, digikata commented
Squashed and ready for next review & merge

2022-10-06 23:11 UTC, sehz requested changes
A couple of nits.   Need to clean up logging and other usages but we can at post-commit

2022-10-06 23:11 UTC, sehz commented on crates/fluvio-hub-util/src/package.rs
> +//! phase1, unpackage file, verify signature
remove these comments

2022-10-06 23:11 UTC, sehz commented on crates/fluvio-hub-util/src/utils.rs
> +            // phase 2 hub-dev
is this comments needed?

2022-10-06 23:11 UTC, sehz commented on crates/fluvio-hub-util/src/utils.rs
> +            // support later, needs hub-pkg-server support
remove these comments

2022-10-07 01:12 UTC, digikata commented
one more cleanup round - resolved all comments and a few more cleanup areas. Resquashed

2022-10-07 01:32 UTC, sehz commented
CI failing

2022-10-07 05:32 UTC, digikata commented
minor test fix, rebased

2022-10-07 20:28 UTC, sehz approved these changes
LGTM

2022-10-07 20:48 UTC, closed without merging