2652 add p package option to smdk to support cargo workspace projects
infinyon/fluvio pull request #2701
Opened 2022-10-15 04:44 UTC by superstator

2022-10-16 04:19 UTC, sehz requested changes
Seem overall look ok.  Few minor nits

2022-10-16 04:19 UTC, sehz commented on crates/smartmodule-development-kit/src/package.rs
> +use std::fs::read_dir;
Just minor nit.  Prefer these conventions for import
```
<std>

<third_party>

<fluvio crates>
<local crate>
<and everything else>
```

2022-10-16 04:19 UTC, sehz commented on crates/smartmodule-development-kit/src/package.rs
> +        let cwd = env::current_dir().expect("Failed to get current working directory");
let's remove expect

2022-10-16 04:19 UTC, sehz commented on crates/smartmodule-development-kit/src/package.rs
> +                .expect("Failed to read directory")
remove expect

2022-10-16 04:19 UTC, sehz commented on crates/smartmodule-development-kit/src/package.rs
> +    pub fn from_options(options: &PackageOption) -> Result<PackageInfo, String> {
add more description to what this fn do

2022-10-16 16:28 UTC, EstebanBorai approved these changes
Other than @sehz comments, LGTM!

2022-10-17 01:43 UTC, sehz approved these changes
LGTM

2022-10-17 01:44 UTC, sehz commented
bors r+

2022-10-17 02:29 UTC, closed without merging