refactor compute_hw with using less memory and less time
infinyon/fluvio pull request #2803
Opened 2022-11-11 18:07 UTC by kranfix

# What does this PR do?

Enhance the algorith used by `compute_hw` in `fluvio-spu`.

# Motivation

The code was difficult to read and also was using to much unnecessary memory with too many nested loops.

2022-11-11 19:43 UTC, EstebanBorai commented
@kranfix great job!

2022-11-12 00:12 UTC, sehz requested changes
Nice optimization.  I didn't realize BinaryHeap could be used instead.
One minor nit

2022-11-12 00:12 UTC, sehz commented on crates/fluvio-spu/src/replication/leader/replica_state.rs
> +    let qualified_leos = BinaryHeap::from(qualified_leos);
can you rename this variable to more precise and not duplicate prev name?

2022-11-12 02:01 UTC, sehz commented
bors r+

2022-11-12 05:55 UTC, kranfix commented
Merged with master for pass some checks and optimized a little more the code.

Having `n=number of qualified leos` and `m=min_lrs=valid min_replica` and `m<=n`

Originally:
- time: `O(n^2)`
- space: `O(n)`

First version of the refactor:
- time: `O(n*log(n))`
- space: `O(n)`

Last version of the refactor:
- time: `O(n*log(m))`
- space: `O(m)`

2022-11-12 16:24 UTC, sehz commented
bors r+

2022-11-12 16:44 UTC, closed without merging