Add cluster status to cli
infinyon/fluvio pull request #2824
Opened 2022-11-21 20:57 UTC by crajcan

### Behavior

Adds `fluvio cluster status` to the CLI

Tries to connect to the SC, reports "none" if unsuccessful, describes where (local/k8s/cloud) cluster is deployed if successful. If the SC is up, it then will report if the SPUs are down, or if they are all empty.

### Comment

I'm not sure if this was still wanted but it looked like a fun first issue. It's also possible I misinterpreted the original request. Specifically, I'm not sure how we could determine if the status should be "stopped (no sc, spu running but data exits)", as I'm not sure how to determine if there is data in the spus if the connection to the sc fails.

I would love some feedback and would be happy to make modifications!

https://github.com/infinyon/fluvio/issues/1673

2022-11-22 16:49 UTC, sehz commented
Running changes show following: 
```
$  flvd cluster status
Cluster Running on local k8s
spus have no data
```

2022-11-22 17:00 UTC, sehz commented
The response should model something like `fluvio cluster start.`  So something like this would be good:

```
$ fluvio cluster status
📝 Running checks using profile 'rancher-desktop`
    ✅ Kubectl active cluster rancher-desktop at: https://127.0.0.1:6443 found
    ✅ SC is ok
    ✅ 2/2 SPU is ok
    ✅ 10 topics with 25G used
```

I will update original ticket as well

2022-11-22 17:04 UTC, sehz requested changes
Nice start.  Updated with better specification

2022-12-06 23:45 UTC, sehz commented on crates/fluvio-cluster/src/cli/status.rs
> +        if size < 1024 {
can you change to use https://crates.io/crates/bytesize?

2022-12-08 04:01 UTC, crajcan commented
> LGTMS. Thanks for contribution!

😄 Thanks for the reviews!

2022-12-08 05:32 UTC, sehz commented
clippy failures

2022-12-08 16:45 UTC, sehz commented
bors r+

2022-12-08 17:16 UTC, closed without merging