Add MySQL CDC example
infinyon/fluvio pull request #315
Opened 2020-09-25 20:13 UTC by nicholastmosher

This PR adds our MySQL CDC example to our `examples/` directory as a set of standalone crates.

This is also where all of the work for porting the CDC example from the old fluvio client to the new one is taking place.

Some things that are left to do:

- [ ] Make the producer read the latest offset in a partition (blocked on #312)
- [ ] In the meantime, I'll make the producer track its own offset in a file on disk
- [ ] Simplify and slim down the code as much as possible
- [ ] Streamline the setup process as much as possible

2020-09-25 21:17 UTC, sehz requested changes

2020-09-25 21:17 UTC, sehz commented on Cargo.toml
> +    "examples/01-cdc/messages",
shouldn't cdc be in a single crate?

2020-09-25 21:17 UTC, sehz commented on examples/01-cdc/README.MD
> +In **flv-mysql-cdc-demo** directory, build producer/consumer
is this correct?

2020-09-25 21:17 UTC, sehz commented on examples/01-cdc/README.MD
> +Compiling cdc-producer v0.1.0 (/projects/github/flv-mysql-cdc-demo/mysql-cdc/cdc-producer)
use example directory?

2020-09-25 21:17 UTC, sehz commented on examples/01-cdc/README.MD
> +./target/debug/cdc-producer ./cdc-producer/producer_profile.toml
use `cargo run`

2020-09-25 21:17 UTC, sehz commented on examples/01-cdc/README.MD
> +./target/debug/cdc-consumer cdc-consumer/consumer_profile.toml
use `cargo run`

2020-09-25 21:17 UTC, sehz commented on examples/01-cdc/README.MD
> +$ ./target/debug/fluvio consume rust-mysql-cdc -B
`cargo run`

2020-09-25 21:17 UTC, sehz commented on examples/01-cdc/consumer/Cargo.toml
> +[package]
consolidate in a single crate?

2020-09-25 21:17 UTC, sehz commented on examples/01-cdc/consumer/Cargo.toml
> +flv-future-aio = "2.2.1"
use `fluvio-future`,  `flv-future-aio` is depecrated

2020-09-25 21:28 UTC, nicholastmosher commented
Sorry @sehz I didn't mean for this to be reviewed yet. I just copied directly from the old demo repo into here and I'm working on cleaning it up incrementally

2020-09-25 21:31 UTC, sehz commented
Ok. Wont review until it is ready

2020-09-28 15:23 UTC, sehz commented
is this ready?

2020-09-28 15:29 UTC, nicholastmosher commented
@sehz not yet, I want to at a minimum consolidate all of the documentation and fix it. I'm sure I messed up some filepaths with all of the moving around. But I want to wait on that until we also have a good Getting Started guide to reference back to so I can make sure it all reads well together.

2020-10-08 19:56 UTC, closed without merging