refactor(smartengine): add abstraction layer for WASM engine
infinyon/fluvio pull request #3257
Opened 2023-05-15 12:41 UTC by xxchan

This PR contains:
- refactor to add an abstraction layer of wasm engine. And refactor wasmtime engine to use the common code. 
- add WasmEdge engine

To run WasmEdge test, install wasmedge: https://wasmedge.org/book/en/quick_start/install.html
``
cargo test -p fluvio-smartengine --features wasmedge-engine
``

I'd like to gain feedbacks about the overall design first. If the general ideas look good, we can take a deeper look and begin to resolve other points (e.g., styling, CI, ...), and maybe split into smaller PRs if necessary.

Some notes:
- Most code & tests are shared by both engines. Only folder `wasmedge` is WasmEdge-specific code, and that's ~300 lines of simple code. To discuss how to maintain WasmEdge related code, and to get the ideas of how the common code work, it might be better to keep WasmEdge related code now. This can actually make it easier to review this PR. I can remove the WasmEdge related code after the code review if that's not decided.
- Since there are some re-org. Maybe it's easier to review by checking out the branch and review locally. (Just a suggestion)

2023-05-16 10:30 UTC, sehz commented
Nice work on adding WasmEdge features.  To make it easier to review, can you split these into two separate PR: (1) non WasEdge related changes so we can merge that (2) WasEdge related code.   We still have to figure out how to support WasEdge features with minimum  impact to Fluvio developers

2023-05-31 14:19 UTC, xxchan commented
WasmEdge code is removed.

2023-05-31 14:32 UTC, xxchan commented
> can you reorder terms in of:
> 
> * std
> * third party
> * fluvio dep

https://github.com/xxchan/fluvio/pull/1#discussion_r1191642981

@sehz Just FYI, there's a rustfmt option (unstable) https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#group_imports

I added
```
group_imports = "StdExternalCrate"
```
and run
```
cargo +nightly fmt -p fluvio-smartengine 
```

Not sure whether you want it for the whole repo, as you use stable toolchian.

2023-05-31 14:45 UTC, xxchan commented on crates/fluvio-smartengine/src/engine/wasmtime/instance.rs
> -impl SmartModuleInstance {
This goes to `common/mod.rs`

2023-05-31 14:46 UTC, xxchan commented on crates/fluvio-smartengine/src/engine/wasmtime/instance.rs
> -pub(crate) trait SmartModuleTransform: Send + Sync {
This goes to `common/transforms/mod.rs`

2023-05-31 14:49 UTC, xxchan commented on crates/fluvio-smartengine/Cargo.toml
> +serde = { workspace = true,  features = ['derive', 'std'] }
previously `std` features is depended by `wasmtime`, I added it when developing WasmEdge

2023-05-31 14:53 UTC, xxchan commented on crates/fluvio-smartengine/src/engine/wasmtime/engine.rs
> -pub struct SmartModuleChainBuilder {
This becomes `src/engine/mod.rs`

2023-05-31 16:25 UTC, sehz commented on crates/fluvio-smartengine/src/engine/common/init.rs
> +        let (ptr, len, version) = instance.write_input(&input, ctx)?;
the prev version used slice abstraction.  is there a reason for changing this?

2023-05-31 16:27 UTC, sehz requested changes

2023-05-31 16:27 UTC, sehz commented on crates/fluvio-smartengine/src/engine/common/mod.rs
> +    ) -> Result<(i32, i32, i32)>;
Use slice abstraction as before

2023-07-31 12:44 UTC, closed without merging