use new CLOUD_URL secret in smartmodule publish
infinyon/fluvio pull request #3347
Opened 2023-06-23 15:47 UTC by ozgrakkurt

2023-06-23 15:55 UTC, sehz requested changes

2023-06-23 15:56 UTC, sehz commented
the argument should only need to specify env (prod/dev)

2023-06-23 15:57 UTC, ozgrakkurt commented on .github/workflows/smartmodule-publish.yml
> +      ORG_CLOUD_URL_DEV:
those have to be passed in order to be used. If we call this workflow from another place and this workflow doesn't have those arguments then it won't work

2023-06-23 15:57 UTC, sehz commented
let workflow here figure ou secrets

2023-06-23 15:57 UTC, ozgrakkurt commented on .github/workflows/smartmodule-publish.yml
> +      ORG_CLOUD_URL_DEV:
the difference is the caller can just do `secrets: inherit` instead of passing them individually

2023-06-23 15:58 UTC, sehz commented on .github/workflows/smartmodule-publish.yml
> +      ORG_CLOUD_URL_DEV:
publisher doesn't not need concern about secrets

2023-06-23 16:17 UTC, ozgrakkurt commented on .github/workflows/smartmodule-publish.yml
> +      ORG_CLOUD_URL_DEV:
removed

2023-06-23 16:21 UTC, sehz commented
Remove the building SmartModule. Should not impose how smartmodule is built.   Instead pass SmartModule artifacts

2023-06-23 16:32 UTC, ozgrakkurt commented
> Remove the building SmartModule. Should not impose how smartmodule is built. Instead pass SmartModule artifacts

I checked the 

> Remove the building SmartModule. Should not impose how smartmodule is built. Instead pass SmartModule artifacts

It is same as https://github.com/infinyon/fluvio/blob/master/.github/workflows/connector-publish.yml#L68C7-L77C42. Not sure how to pass smartmodule artifacts

2023-06-23 16:34 UTC, sehz commented
We want to avoid the same mistake in that workflow.   see here for how to pass https://stackoverflow.com/questions/60355925/share-artifacts-between-workflows-github-actions

2023-06-23 16:48 UTC, sehz commented
Because each SmartModule/Connector may need a slightly different way to build in the future, it's the separation of concern. Publishing should not be concerned with how artifacts are built.   Less opinionated is generally better

2023-06-28 15:04 UTC, ozgrakkurt commented
trying to go through with this but needs https://github.com/infinyon/fluvio/pull/3352 at least. Imo we should just merge this and look at this improvement later

2023-07-03 16:58 UTC, ozgrakkurt commented
currently blocked by https://github.com/infinyon/fluvio/issues/3365

2023-07-10 02:53 UTC, ozgrakkurt commented
@sehz can you check again?

I verified this kind of setup works with these:
- [re-usable workflow](https://github.com/data-indexing/reusable-workflow/blob/main/.github/workflows/download-artifact.yaml)
- [caller workflow](https://github.com/data-indexing/caller-workflow/blob/main/.github/workflows/call.yaml)
- [workflow run](https://github.com/data-indexing/caller-workflow/actions/runs/5503444011)

2023-07-10 02:56 UTC, sehz approved these changes
K.  LGTM

2023-07-10 02:58 UTC, ozgrakkurt commented
bors r+

2023-07-10 03:26 UTC, closed without merging