Unify common dependencies
infinyon/fluvio pull request #3442
Opened 2023-08-03 19:03 UTC by c410-f3r

Continuation of #3408

To the best of my knowledge, all common dependencies are now sharing the same workspace definition.

2023-08-03 19:06 UTC, c410-f3r commented on Cargo.toml
>  [workspace]
Besides the inclusion of more workspace dependencies, some items were re-ordered to make manual looks-up a bit easier

2023-08-07 18:27 UTC, c410-f3r commented
Looks like https://github.com/infinyon/fluvio/actions/runs/5754781767/job/15601307131 was spurious but now https://github.com/infinyon/fluvio/actions/runs/5788343499/job/15687610521?pr=3442 is showing a version mismatch. Needs more investigation on my side.

2023-08-10 21:53 UTC, c410-f3r commented
@EstebanBorai CI looks OK now

2023-08-10 22:22 UTC, EstebanBorai approved these changes
Thanks @c410-f3r! Nice work!

2023-08-14 17:04 UTC, sehz requested changes
all looks good except `trybuild` on a repo

2023-08-14 17:04 UTC, sehz commented on crates/fluvio-test-case-derive/Cargo.toml
> +trybuild = { workspace = true }
this is not same `trybuild`  keep as is

2023-08-14 17:19 UTC, sehz approved these changes
LGTM.  Thanks

2023-08-14 17:21 UTC, c410-f3r commented
Thank you guys!

2023-08-14 19:34 UTC, c410-f3r commented
> Socket io Timed out: 60 secs waiting for response. API_KEY=1001, CorrelationId=5

Error looks spurious

2023-08-14 20:37 UTC, EstebanBorai commented
bors r+

2023-08-14 21:21 UTC, morenol commented
bors r+

2023-08-14 21:47 UTC, morenol commented
bors retry

2023-08-14 22:13 UTC, closed without merging

2023-08-15 11:04 UTC, c410-f3r commented
Thank you @morenol !