chore: clone `smdk test` to `fluvio sm test`
infinyon/fluvio pull request #3559
Opened 2023-09-26 14:26 UTC by matheus-consoli

Closes #3553

Moves most of the `TestCdm` from the smdk to `fluvio-cli-common` and reutilizes it from `fluvio-cli` and `smartmodule-development-kit`.

The API for `smdk` is unchanged.

The API for `fluvio sm test` is mostly the same, except for removing:

```sh
      --release <RELEASE>                  Release profile name [default: release-lto]
  -p, --package-name <PACKAGE_NAME>        Optional package/project name
      --wasm-file <WASM_FILE>              Optional wasm file path
```

## Testing

Download a SM from the hub:

```sh
fluvio hub download infinyon/regex-filter@0.1.0
```

and run a test for it:

```sh
fluvio sm test -t '{"uses":"infinyon/regex-filter@0.1.0", "with": {"regex": "^fl"}}' --text 'fluvio' 
```

![fluvio-cli-sm](https://github.com/infinyon/fluvio/assets/27595790/6ee931cc-e3bc-45b8-a392-7773899a7a4c)

2023-09-26 15:47 UTC, sehz commented
also `smdk test` and `fluvio test` is two different.  `smdk` is for supporting developer while `fluvio` is for regular user.  `fluvio test` should test only downloaded SmartModule on cluster

2023-09-26 21:45 UTC, matheus-consoli commented
CI is failing again, but it's not related to the changes:

```
Run make cli-partition-test-multiple-partitions
...
Producer error: Producer received an error code: the given SPU is not the leader for the partition
```

2023-09-27 18:32 UTC, sehz requested changes
Please add CLI test

2023-09-28 21:37 UTC, tjtelan approved these changes
lgtm!

2023-10-30 15:55 UTC, digikata commented
@matheus-consoli can you open a separate issue for the ci service account for the failing test on this pr and the other one and assign it to me?    Since this passes on local tests, lets merge that and I'll take a look at the auth separately.

2023-10-31 21:40 UTC, digikata commented
> Can we just create mock hub server them instead of trying to hub actually?

Yes, but I'd like to keep a live hub check test around for in pre release checks, a mock hub server is probably best for regular CI automation - but lets think about how to structure that on the follow on CI #3634 issue.  And get this pr merged.

2023-11-01 18:56 UTC, matheus-consoli commented
smoke-test-k8 failed but it's not related to the changes here

bors retry

2023-11-01 21:07 UTC, matheus-consoli commented
bors r+

2023-11-03 15:07 UTC, matheus-consoli commented
bors retry

2023-11-14 04:09 UTC, digikata approved these changes

2023-11-17 16:34 UTC, merged