feat: introduce `Fluvio Version Manager`
infinyon/fluvio pull request #3562
Opened 2023-09-28 20:28 UTC by EstebanBorai

Introduces the FVM (Fluvio Version Manager) with support for:

- Installing `stable`, `latest` and a specific Fluvio Version
- Fresh Fluvio Installer solution
- Switch between Fluvio Versions

2023-09-28 21:01 UTC, sehz requested changes
first pass.  comments are in these groups:
- move to anyhow, that will get rid of vast defined error
- reduce output, don't need to inform user every actions, use tracing
- move all package related abstraction to hub or something.  it's not responsibility of FVM to provide these abstraction
- FVM should deal with channel abstraction not package 
- need more test

2023-09-28 21:02 UTC, sehz commented
Probably better break this into smaller PR.

2023-09-29 00:34 UTC, EstebanBorai commented
Thanks for the feedback @sehz!

I think moving into a smaller PR will be a good approach to achieve this.

Will apply improvements as I move into smaller PRs.

2023-09-29 01:59 UTC, EstebanBorai commented
This PR will be split into the following parts:

- [ ] Introduce FVM for Hub Util
- [ ] FVM
  - [ ] Introduce `fvm self` commands
  - [ ] Introduce `fvm install` command
  - [ ] Introduce `fvm switch` command
  - [ ] Introduce `fvm current` and `fvm show` command

2023-09-29 03:01 UTC, sehz commented
Suggest to break down into these ares
- ChannelManager.  This will be responsible for managing channels
- Download/Updater.    Download hub pkg required from ChannelManager
- Then FVM CLI which should be just wrapper for CLI command (show progress, etc).

2023-09-29 14:28 UTC, digikata commented on crates/fvm/src/bin/command/install.rs
> +        let pkgset = install_task.fetch_pkgset().await?;
here pkgset is what is being stored in the hub.  package is a bit misleading but pkgset is a separate term.

2023-09-29 15:56 UTC, EstebanBorai commented on crates/fluvio-hub-util/src/fvm.rs
> +
This represents the supported build targets for Fluvio as available in CI, took this list from: https://github.com/infinyon/fluvio/blob/f2c49e126c771d58d24d5f5cb0282a6aaa6b23ca/.github/workflows/ci.yml#L141

2023-09-29 17:00 UTC, EstebanBorai commented
> Suggest to break down into these ares
> 
> * ChannelManager.  This will be responsible for managing channels
> * Download/Updater.    Download hub pkg required from ChannelManager
> * Then FVM CLI which should be just wrapper for CLI command (show progress, etc).

First decoupling step lives here: https://github.com/infinyon/fluvio/pull/3566 I am aiming to provide FVM/Hub API HTTP Client responsible of fetching binaries URLs from the Hub.

Also unit tests and new type definitions.

2023-10-11 22:22 UTC, closed without merging