[Merged by Bors] - feat: use local metadata for local clusters
infinyon/fluvio pull request #3617
Opened 2023-10-23 13:18 UTC by galibey

Use `LocalMetadataStorage` as a metadata backend for local clusters created by `fluvio cluster start --local`. It allows running fluvio cluster without K8.

To use K8 as a metadata backend for local clusters introduced `fluvio cluster start --local-k8` option.

2023-10-24 15:21 UTC, sehz requested changes
Overall looks good.  My main comments about make sure we don't have duplicate code and testing to ensure consistent behavior

2023-10-24 22:05 UTC, sehz commented on .github/workflows/ci.yml
> +    runs-on: ${{ matrix.os }}
it's not marginal run mode.  this performs full sets of partition focus test for K8

2023-10-24 22:15 UTC, sehz commented on crates/fluvio-sc/src/start.rs
> -fn inner_main_loop<C>(
remove proxy code duplication

2023-10-25 06:08 UTC, galibey commented on .github/workflows/ci.yml
> +    runs-on: ${{ matrix.os }}
Added `local-k8` run mode to check against the full test suite.

2023-10-25 06:09 UTC, galibey commented on crates/fluvio-sc/src/start.rs
> -fn inner_main_loop<C>(
Done

2023-10-25 16:02 UTC, sehz approved these changes
LGTM

2023-10-27 06:16 UTC, galibey commented
bors r+

2023-10-27 06:53 UTC, closed without merging