feat: close producer when topic is deleted
infinyon/fluvio pull request #4147
Opened 2024-08-21 23:57 UTC by fraidev

2024-08-22 14:56 UTC, sehz requested changes
I don't think this is right approach.  This should work for all client not just CLI.  client should detect if topic is closed then close connection

2024-08-22 14:56 UTC, sehz commented on crates/fluvio-cli/Cargo.toml
> +async-std = { workspace = true }
don't bring in `async-std`.

2024-08-22 17:33 UTC, fraidev commented
> I don't think this is right approach. This should work for all client not just CLI. client should detect if topic is closed then close connection

Make sense! But the producer is never what is blocking. 
In this case, the blocker is the stdin and for connectors the source stream that is blocking:

```rust
#[connector(source)]
async fn start(config: CustomConfig, producer: TopicProducerPool) -> Result<()> {
    let source = TestJsonSource::new(&config)?;
    let mut stream = source.connect(None).await?;
    while let Some(item) = stream.next().await {
        println!("producing a value: {}", &item);
        producer.send(RecordKey::NULL, item).await?;
    }
    Ok(())
}
```

Maybe we can change TopicProducerPool to detect an error when the topic is deleted and also add a method to detect it, but we will also need to add something like `select!` and change uses of the producer.

Another solution that I had is have a method that receives a stream and returns a stream that handles it.

```bash    
async fn from_stream(stream: GenericStream) -> ProducerStream
```

But we will need change implementations too:

```rust
#[connector(source)]
async fn start(config: CustomConfig, producer: TopicProducerPool) -> Result<()> {
    let source = TestJsonSource::new(&config)?;
    let mut stream = source.connect(None).await?;
    while let Some(item) = producer.from_stream(stream).await {
        println!("producing a value: {}", &item);
        producer.send(RecordKey::NULL, item).await?;
    }
    Ok(())
}
```

What do you think?

2024-08-26 15:15 UTC, digikata commented
Is cluster side socket already closed by the SPU?  I think that's the first thing to handle for this case.  In addition, if possible it would be nice for the SPU to send a message that the produce stream is being closed due to topic delete, and then close the spu side socket.

2024-08-26 16:07 UTC, fraidev commented
> Is cluster side socket already closed by the SPU? I think that's the first thing to handle for this case. In addition, if possible it would be nice for the SPU to send a message that the produce stream is being closed due to topic delete, and then close the spu side socket.

Yeah, I think so. The SPU already send a `TopicNotFound` error when does not find it.

But I think that we will have the same problem. All usage of producer seems to be:

- Await an input
- Produce it

The `Produce it` part will return the SPU error, but it will be trigger only after the input.

I think that this issue aims to be notified before the input.

2024-11-03 11:19 UTC, closed without merging