Search $FLUVIO_DIR and $HOME/.fluvio/extensions for extension executable
infinyon/fluvio pull request #508
Opened 2020-11-23 18:43 UTC by simlay

This will close #500.

2020-11-23 20:56 UTC, simlay commented on src/cli/src/install/mod.rs
> -        dirs::home_dir().ok_or_else(|| IoError::new(ErrorKind::NotFound, "Homedir not found"))?;
https://github.com/rust-lang/rust/issues/43321 relevant

2020-11-24 02:47 UTC, sehz requested changes
Looks good.  What about removing warning about PATH in the installer?

2020-11-24 02:52 UTC, simlay commented
> What about removing warning about PATH in the installer?

Whoops. Forgot about that. Where do we want the installer to install to? `/usr/local/bin`? I actually kinda like it getting installed at `~/.fluvio/bin`.

2020-11-24 02:55 UTC, sehz commented
> > What about removing warning about PATH in the installer?
> 
> Whoops. Forgot about that. Where do we want the installer to install to? `/usr/local/bin`? I actually kinda like it getting installed at `~/.fluvio/bin`.

I see.  if it is installed at `~/.fluvio/bin`, we still need have user modify PATH

2020-11-24 04:31 UTC, sehz approved these changes

2020-11-24 04:43 UTC, merged