Add cargo-make task for minikube-image
infinyon/fluvio pull request #603
Opened 2020-12-23 15:21 UTC by nicholastmosher

I've added some cargo-make tasks that mirror other ones that have worked well for us. I'm able to successfully build the musl images on Mac.

One thing I'm stuck on though is that `fluvio cluster start --develop` does not seem to be picking up on these new images, I'm getting `ErrImagePull` on the pods that come up. @nacardin is there anything extra that needs doing to these docker images for them to be seen?

2020-12-23 16:16 UTC, nacardin commented
Should we remove duplicate functionality from the GNU makefile? Maybe we can remove `fluvio_bin_linux` and point `fluvio_image` and `minikube_image` to run `cargo make`

2020-12-23 16:49 UTC, sehz commented
Yes, we should remove duplication.  But need to make sure we don't have regression in performance and other workflows.  The linux build should be using `cargo build` as before.   Other non-unix platform can use docker based cross-compiler

2020-12-23 17:10 UTC, nicholastmosher commented
@sehz this actually is not using the `cross build` tool that uses Docker images for compilation. This is using plain-old cargo but it has all the right configurations to make the musl target build properly. I will make sure we have a way to invoke build for the particular targets we want

2020-12-23 17:22 UTC, nicholastmosher commented
@nacardin I just briefly looked through the Makefile looking for isolated pieces that I could pull out, but I realized that it's pretty tangled up right now and I don't trust myself to modify it without any regressions without a lot of careful work. I think we already have issues open for migrating to cargo-make, maybe we can leave that work for those issues in the future.

2020-12-24 18:03 UTC, nicholastmosher commented
@sehz and @nacardin is there anything you would like to see changed here before merging?

2020-12-24 19:18 UTC, sehz commented
rebase

2020-12-24 21:27 UTC, sehz requested changes

2020-12-24 21:27 UTC, sehz commented on makefiles/Build.toml
> +extend = "Base.toml"
is this being used? if not, we should merge this later when this is integrated.  Other changes looks good

2020-12-24 21:27 UTC, sehz commented
rebase

2021-03-24 19:32 UTC, sehz commented
Is this still relevant?

2021-03-25 13:41 UTC, nicholastmosher commented
I think everything we needed from this has been taken care of elsewhere

2021-03-25 13:41 UTC, closed without merging