Made consumer module pub
infinyon/fluvio pull request #687
Opened 2021-01-14 20:42 UTC by simlay

This makes infinyon/fluvio-client-node#66 much cleaner and it will also help with our rust client users.

2021-01-14 20:44 UTC, simlay commented on src/client/src/consumer.rs
> +    /// [KIP-74](https://cwiki.apache.org/confluence/display/KAFKA/KIP-74%3A+Add+Fetch+Response+Size+Limit+in+Bytes)
I found this someplace in the fluvio src as a reference but I'm not sure it's correct.

2021-01-14 20:46 UTC, sehz requested changes

2021-01-14 20:46 UTC, sehz commented on src/client/src/consumer.rs
> +    /// [KIP-74](https://cwiki.apache.org/confluence/display/KAFKA/KIP-74%3A+Add+Fetch+Response+Size+Limit+in+Bytes)
remove ref to kafka

2021-01-14 20:46 UTC, sehz commented on src/client/src/lib.rs
> +pub mod consumer;
Don't think we want to expose entire module yet.  @nicholastmosher concur?
Let's just expose what is need for this change

2021-01-15 20:14 UTC, sehz approved these changes

2021-01-15 20:14 UTC, sehz commented
rebase please

2021-01-15 21:20 UTC, merged