Reproduce timeout bug in consumer
infinyon/fluvio pull request #804
Opened 2021-02-19 16:18 UTC by nicholastmosher

2021-02-19 17:09 UTC, sehz requested changes

2021-02-19 17:09 UTC, sehz commented on tests/runner/src/test_runner.rs
> +                .arg("test-bug")
changed to something more meaningful `test-concurrent`

2021-02-19 17:09 UTC, sehz commented on tests/runner/src/tests/smoke/concurrent.rs
> +const TOPIC: &str = "test-bug";
use the topic name int the test runner

2021-02-19 17:09 UTC, sehz commented on tests/runner/src/tests/smoke/mod.rs
> -            let start_offsets = super::produce::produce_message(&self.option).await;
kick off concurrent test depends on test flag

2021-04-08 15:15 UTC, nicholastmosher commented
Superseded by new test runner

2021-04-08 15:15 UTC, closed without merging