Add Hourly tests
infinyon/fluvio pull request #963
Opened 2021-04-15 19:52 UTC by tjtelan

Split off of #923 

Add new hourly test job which will run smoke and performance tests at the beginning of every hour.

Resolves #924

2021-04-16 18:56 UTC, nicholastmosher commented on .github/workflows/hourly.yml
> +      #  - Matrix: local, k8
There is no `local` in the matrix

2021-04-16 18:57 UTC, nicholastmosher commented on .github/workflows/hourly.yml
> +        run: brew install sccache
There was a brownout of brew the other day, I believe they want people to use the newest version (or newest repos?) on brew. Can you make this into

```
run: |
  brew update
  brew install sccache
```

2021-04-16 18:58 UTC, nicholastmosher commented
Looks good. Can you do the same thing here where you just include changes for hourly on this PR and leave benchmark stuff in the other PR?

2021-04-16 19:27 UTC, tjtelan commented
> Looks good. Can you do the same thing here where you just include changes for hourly on this PR and leave benchmark stuff in the other PR?

I need the benchmark stuff to merge first before this one. I am running the `producer_stress` test in benchmark mode.

2021-04-16 19:27 UTC, sehz requested changes
LGMT.  couple of minor nits

2021-04-16 19:27 UTC, sehz commented on .github/workflows/hourly.yml
> +            cmd: cargo run --release --bin flv-test -- smoke --develop --disable-install -- --producer-iteration 100 --producer-record-size 1000
can you put producer-iteration and producer recored size as env parameter in the job?

2021-04-16 21:49 UTC, sehz commented
rebase

2021-04-17 01:05 UTC, sehz approved these changes
We can defer some cleanup in later PR

2021-04-17 01:06 UTC, sehz commented
bors r+

2021-04-17 01:35 UTC, closed without merging